package ec.fe.tickets.model;
// Generated Jul 17, 2015 5:12:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TtFarmacia generated by hbm2java
 */
@Entity
@Table(name="TT_Farmacia"
    ,schema="dbo"
    ,catalog="Tickets"
)
public class TtFarmacia  implements java.io.Serializable {


     private String farIdFarmacia;
     private TtProveedor ttProveedor;
     private String farPiloto;
     private String farTelfConvencional;
     private String farTelfCelular;
     private String farIp;
     private Boolean farEstado;
     private String farDireccion;
     private String farCoordenadas;
     private String farMedio;
     private String farVelocidad;
     private String farCosto;
     private String farEsFranquicia;
     private String farFranquiciado;
     private String farNumBodega;
     private Integer farCentroCosto;
     private Integer farOficina;
     private String farCiudad;
     private Set ttTickets = new HashSet(0);

    public TtFarmacia() {
    }

	
    public TtFarmacia(String farIdFarmacia, String farTelfConvencional) {
        this.farIdFarmacia = farIdFarmacia;
        this.farTelfConvencional = farTelfConvencional;
    }
    public TtFarmacia(String farIdFarmacia, TtProveedor ttProveedor, String farPiloto, String farTelfConvencional, String farTelfCelular, String farIp, Boolean farEstado, String farDireccion, String farCoordenadas, String farMedio, String farVelocidad, String farCosto, String farEsFranquicia, String farFranquiciado, String farNumBodega, Integer farCentroCosto, Integer farOficina, String farCiudad, Set ttTickets) {
       this.farIdFarmacia = farIdFarmacia;
       this.ttProveedor = ttProveedor;
       this.farPiloto = farPiloto;
       this.farTelfConvencional = farTelfConvencional;
       this.farTelfCelular = farTelfCelular;
       this.farIp = farIp;
       this.farEstado = farEstado;
       this.farDireccion = farDireccion;
       this.farCoordenadas = farCoordenadas;
       this.farMedio = farMedio;
       this.farVelocidad = farVelocidad;
       this.farCosto = farCosto;
       this.farEsFranquicia = farEsFranquicia;
       this.farFranquiciado = farFranquiciado;
       this.farNumBodega = farNumBodega;
       this.farCentroCosto = farCentroCosto;
       this.farOficina = farOficina;
       this.farCiudad = farCiudad;
       this.ttTickets = ttTickets;
    }
   
     @Id 

    
    @Column(name="far_id_farmacia", unique=true, nullable=false, length=300)
    public String getFarIdFarmacia() {
        return this.farIdFarmacia;
    }
    
    public void setFarIdFarmacia(String farIdFarmacia) {
        this.farIdFarmacia = farIdFarmacia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="far_fk_id_proveedor")
    public TtProveedor getTtProveedor() {
        return this.ttProveedor;
    }
    
    public void setTtProveedor(TtProveedor ttProveedor) {
        this.ttProveedor = ttProveedor;
    }

    
    @Column(name="far_piloto", length=300)
    public String getFarPiloto() {
        return this.farPiloto;
    }
    
    public void setFarPiloto(String farPiloto) {
        this.farPiloto = farPiloto;
    }

    
    @Column(name="far_telf_convencional", nullable=false, length=300)
    public String getFarTelfConvencional() {
        return this.farTelfConvencional;
    }
    
    public void setFarTelfConvencional(String farTelfConvencional) {
        this.farTelfConvencional = farTelfConvencional;
    }

    
    @Column(name="far_telf_celular", length=300)
    public String getFarTelfCelular() {
        return this.farTelfCelular;
    }
    
    public void setFarTelfCelular(String farTelfCelular) {
        this.farTelfCelular = farTelfCelular;
    }

    
    @Column(name="far_ip", length=15)
    public String getFarIp() {
        return this.farIp;
    }
    
    public void setFarIp(String farIp) {
        this.farIp = farIp;
    }

    
    @Column(name="far_estado")
    public Boolean getFarEstado() {
        return this.farEstado;
    }
    
    public void setFarEstado(Boolean farEstado) {
        this.farEstado = farEstado;
    }

    
    @Column(name="far_direccion", length=300)
    public String getFarDireccion() {
        return this.farDireccion;
    }
    
    public void setFarDireccion(String farDireccion) {
        this.farDireccion = farDireccion;
    }

    
    @Column(name="far_coordenadas", length=300)
    public String getFarCoordenadas() {
        return this.farCoordenadas;
    }
    
    public void setFarCoordenadas(String farCoordenadas) {
        this.farCoordenadas = farCoordenadas;
    }

    
    @Column(name="far_medio", length=300)
    public String getFarMedio() {
        return this.farMedio;
    }
    
    public void setFarMedio(String farMedio) {
        this.farMedio = farMedio;
    }

    
    @Column(name="far_velocidad", length=300)
    public String getFarVelocidad() {
        return this.farVelocidad;
    }
    
    public void setFarVelocidad(String farVelocidad) {
        this.farVelocidad = farVelocidad;
    }

    
    @Column(name="far_costo", length=300)
    public String getFarCosto() {
        return this.farCosto;
    }
    
    public void setFarCosto(String farCosto) {
        this.farCosto = farCosto;
    }

    
    @Column(name="far_es_franquicia", length=300)
    public String getFarEsFranquicia() {
        return this.farEsFranquicia;
    }
    
    public void setFarEsFranquicia(String farEsFranquicia) {
        this.farEsFranquicia = farEsFranquicia;
    }

    
    @Column(name="far_franquiciado", length=300)
    public String getFarFranquiciado() {
        return this.farFranquiciado;
    }
    
    public void setFarFranquiciado(String farFranquiciado) {
        this.farFranquiciado = farFranquiciado;
    }

    
    @Column(name="far_num_bodega", length=300)
    public String getFarNumBodega() {
        return this.farNumBodega;
    }
    
    public void setFarNumBodega(String farNumBodega) {
        this.farNumBodega = farNumBodega;
    }

    
    @Column(name="far_centro_costo")
    public Integer getFarCentroCosto() {
        return this.farCentroCosto;
    }
    
    public void setFarCentroCosto(Integer farCentroCosto) {
        this.farCentroCosto = farCentroCosto;
    }

    
    @Column(name="far_oficina")
    public Integer getFarOficina() {
        return this.farOficina;
    }
    
    public void setFarOficina(Integer farOficina) {
        this.farOficina = farOficina;
    }

    
    @Column(name="far_ciudad", length=300)
    public String getFarCiudad() {
        return this.farCiudad;
    }
    
    public void setFarCiudad(String farCiudad) {
        this.farCiudad = farCiudad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ttFarmacia")
    public Set getTtTickets() {
        return this.ttTickets;
    }
    
    public void setTtTickets(Set ttTickets) {
        this.ttTickets = ttTickets;
    }




}


