package ec.fe.tickets.model;
// Generated Jul 17, 2015 5:12:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TtProveedor generated by hbm2java
 */
@Entity
@Table(name="TT_Proveedor"
    ,schema="dbo"
    ,catalog="Tickets"
)
public class TtProveedor  implements java.io.Serializable {


     private String proIdProveedor;
     private String proContacto1;
     private String proContacto2;
     private String proCorreo;
     private String proEscalamiento1;
     private String proEscalamiento2;
     private String proEscalamiento3;
     private String proEscalamiento4;
     private Set ttFarmacias = new HashSet(0);

    public TtProveedor() {
    }

	
    public TtProveedor(String proIdProveedor, String proContacto1, String proCorreo, String proEscalamiento1) {
        this.proIdProveedor = proIdProveedor;
        this.proContacto1 = proContacto1;
        this.proCorreo = proCorreo;
        this.proEscalamiento1 = proEscalamiento1;
    }
    public TtProveedor(String proIdProveedor, String proContacto1, String proContacto2, String proCorreo, String proEscalamiento1, String proEscalamiento2, String proEscalamiento3, String proEscalamiento4, Set ttFarmacias) {
       this.proIdProveedor = proIdProveedor;
       this.proContacto1 = proContacto1;
       this.proContacto2 = proContacto2;
       this.proCorreo = proCorreo;
       this.proEscalamiento1 = proEscalamiento1;
       this.proEscalamiento2 = proEscalamiento2;
       this.proEscalamiento3 = proEscalamiento3;
       this.proEscalamiento4 = proEscalamiento4;
       this.ttFarmacias = ttFarmacias;
    }
   
     @Id 

    
    @Column(name="pro_id_proveedor", unique=true, nullable=false, length=50)
    public String getProIdProveedor() {
        return this.proIdProveedor;
    }
    
    public void setProIdProveedor(String proIdProveedor) {
        this.proIdProveedor = proIdProveedor;
    }

    
    @Column(name="pro_contacto1", nullable=false, length=100)
    public String getProContacto1() {
        return this.proContacto1;
    }
    
    public void setProContacto1(String proContacto1) {
        this.proContacto1 = proContacto1;
    }

    
    @Column(name="pro_contacto2", length=50)
    public String getProContacto2() {
        return this.proContacto2;
    }
    
    public void setProContacto2(String proContacto2) {
        this.proContacto2 = proContacto2;
    }

    
    @Column(name="pro_correo", nullable=false, length=100)
    public String getProCorreo() {
        return this.proCorreo;
    }
    
    public void setProCorreo(String proCorreo) {
        this.proCorreo = proCorreo;
    }

    
    @Column(name="pro_escalamiento1", nullable=false, length=300)
    public String getProEscalamiento1() {
        return this.proEscalamiento1;
    }
    
    public void setProEscalamiento1(String proEscalamiento1) {
        this.proEscalamiento1 = proEscalamiento1;
    }

    
    @Column(name="pro_escalamiento2", length=300)
    public String getProEscalamiento2() {
        return this.proEscalamiento2;
    }
    
    public void setProEscalamiento2(String proEscalamiento2) {
        this.proEscalamiento2 = proEscalamiento2;
    }

    
    @Column(name="pro_escalamiento3", length=300)
    public String getProEscalamiento3() {
        return this.proEscalamiento3;
    }
    
    public void setProEscalamiento3(String proEscalamiento3) {
        this.proEscalamiento3 = proEscalamiento3;
    }

    
    @Column(name="pro_escalamiento4", length=300)
    public String getProEscalamiento4() {
        return this.proEscalamiento4;
    }
    
    public void setProEscalamiento4(String proEscalamiento4) {
        this.proEscalamiento4 = proEscalamiento4;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ttProveedor")
    public Set getTtFarmacias() {
        return this.ttFarmacias;
    }
    
    public void setTtFarmacias(Set ttFarmacias) {
        this.ttFarmacias = ttFarmacias;
    }




}


