package ec.fe.tickets.model;
// Generated Jul 17, 2015 5:12:36 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtTicket generated by hbm2java
 */
@Entity
@Table(name="TT_Ticket"
    ,schema="dbo"
    ,catalog="Tickets"
)
public class TtTicket  implements java.io.Serializable {


     private int ttIdTicket;
     private TtFarmacia ttFarmacia;
     private Boolean ttEstado;
     private String ttUsuarioReporte;
     private Date ttFechaReporte;
     private Date ttFechaCierre;
     private String ttObservaciones;
     private String ttNumeroTicket;

    public TtTicket() {
    }

	
    public TtTicket(int ttIdTicket) {
        this.ttIdTicket = ttIdTicket;
    }
    public TtTicket(int ttIdTicket, TtFarmacia ttFarmacia, Boolean ttEstado, String ttUsuarioReporte, Date ttFechaReporte, Date ttFechaCierre, String ttObservaciones, String ttNumeroTicket) {
       this.ttIdTicket = ttIdTicket;
       this.ttFarmacia = ttFarmacia;
       this.ttEstado = ttEstado;
       this.ttUsuarioReporte = ttUsuarioReporte;
       this.ttFechaReporte = ttFechaReporte;
       this.ttFechaCierre = ttFechaCierre;
       this.ttObservaciones = ttObservaciones;
       this.ttNumeroTicket = ttNumeroTicket;
    }
    public TtTicket(TtFarmacia ttFarmacia, Boolean ttEstado, String ttUsuarioReporte, Date ttFechaReporte) {       
       this.ttFarmacia = ttFarmacia;
       this.ttEstado = ttEstado;
       this.ttUsuarioReporte = ttUsuarioReporte;
       this.ttFechaReporte = ttFechaReporte;    
    }
   
     @Id 

    
    @Column(name="tt_id_ticket", unique=true, nullable=false)
    public int getTtIdTicket() {
        return this.ttIdTicket;
    }
    
    public void setTtIdTicket(int ttIdTicket) {
        this.ttIdTicket = ttIdTicket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tt_fk_id_farmacia")
    public TtFarmacia getTtFarmacia() {
        return this.ttFarmacia;
    }
    
    public void setTtFarmacia(TtFarmacia ttFarmacia) {
        this.ttFarmacia = ttFarmacia;
    }

    
    @Column(name="tt_estado")
    public Boolean getTtEstado() {
        return this.ttEstado;
    }
    
    public void setTtEstado(Boolean ttEstado) {
        this.ttEstado = ttEstado;
    }

    
    @Column(name="tt_usuario_reporte", length=10)
    public String getTtUsuarioReporte() {
        return this.ttUsuarioReporte;
    }
    
    public void setTtUsuarioReporte(String ttUsuarioReporte) {
        this.ttUsuarioReporte = ttUsuarioReporte;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tt_fecha_reporte", length=23)
    public Date getTtFechaReporte() {
        return this.ttFechaReporte;
    }
    
    public void setTtFechaReporte(Date ttFechaReporte) {
        this.ttFechaReporte = ttFechaReporte;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tt_fecha_cierre", length=23)
    public Date getTtFechaCierre() {
        return this.ttFechaCierre;
    }
    
    public void setTtFechaCierre(Date ttFechaCierre) {
        this.ttFechaCierre = ttFechaCierre;
    }

    
    @Column(name="tt_observaciones", length=500)
    public String getTtObservaciones() {
        return this.ttObservaciones;
    }
    
    public void setTtObservaciones(String ttObservaciones) {
        this.ttObservaciones = ttObservaciones;
    }

    
    @Column(name="tt_numero_ticket", length=80)
    public String getTtNumeroTicket() {
        return this.ttNumeroTicket;
    }
    
    public void setTtNumeroTicket(String ttNumeroTicket) {
        this.ttNumeroTicket = ttNumeroTicket;
    }




}


